home:
    path:     /
    defaults: { _controller: MAGMAAppBundle:Chat:index }
login:
    pattern:  /login
    defaults: { _controller: MAGMAAppBundle:Login:login }
logout:
    pattern:  /logout
    defaults: { _controller: MAGMAAppBundle:Login:logout }
register:
    pattern:  /register
    defaults: { _controller: MAGMAAppBundle:User:register }   
user:
    pattern:  /user/{id}
    defaults: { _controller: MAGMAAppBundle:User:item }
chat:
    pattern:  /chat/{id}
    defaults: { _controller: MAGMAAppBundle:Chat:item }
